inherit_mode:
  merge:
    - Exclude
    - Include

require:
  - rubocop-erb
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-factory_bot: false

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - class_methods
    - concerning
    - context
    - create_table
    - factory
    - FactoryBot.define
    - should
    - should_eventually
  Exclude:
    - config/routes.rb
    - db/seeds.rb
    - db/seeds/*.rb

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpStatus:
  EnforcedStyle: numeric

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb
    - db/seeds/*.rb
    - db/fixes/*.rb
  Include:
    - test/**/*.rb

Rails/ReversibleMigration:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

Rails/WhereExists:
  EnforcedStyle: exists

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FloatDivision:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MapIntoArray:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PerlBackrefs:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Rails/DynamicFindBy:
  Enabled: true
  AllowedMethods:
    - find_by_normalized_name_or_id
    - find_by_normalized_name
    - find_by_name_list

Rails/TimeZoneAssignment:
  Enabled: true
  Exclude:
    - test/**/*.rb

Lint/UriEscapeUnescape:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true
  Exclude:
    - app/logical/moderator/dashboard/queries/*.rb
