#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["RAILS_ENV"] ||= "production"
require File.expand_path(File.join(File.dirname(__FILE__), "..", "..", "config", "environment"))
unless Rails.env.production?
  puts("Skipping db export, not running in production mode")
  exit(0)
end

date = `date +"%Y-%m-%d"`[..-2]

target = ENV.fetch("TARGET_DIR", "/data/db_exports")

error = false
Dir["#{File.dirname(__FILE__)}/*.sql"].each do |file|
  name = File.basename(file)[..-5]
  next if File.exist?("#{target}/#{date}-#{name}.csv.xz")
  contents = File.read(file)
  system(%{psql -h postgres --username pawsmovin -c "COPY (#{contents}) TO STDOUT DELIMITER ',' CSV HEADER;" pawsmovin > "#{target}/#{date}-#{name}.csv"}, exception: true)
  system(%(xz "#{target}/#{date}-#{name}.csv"), exception: true)
  puts("#{name} done")
rescue RuntimeError => e
  puts("Error (#{name}): #{e}")
  FileUtils.rm("#{target}/#{date}-#{name}.csv", force: true)
  FileUtils.rm("#{target}/#{date}-#{name}.csv.xz", force: true)
  error = true
  break
end

if error
  puts("Skipping cleaning up old files due to errored state")
  Dir["#{target}/#{date}-*.csv.xz"].each do |file|
    puts("Removing #{file}")
    FileUtils.rm(file, force: true)
  end
else
  puts("Cleaning up old files")
  Dir["#{target}/*.csv.xz"].each do |file|
    d = File.basename(file)[0..9]
    if Time.zone.parse(d) < 4.days.ago
      puts("Removing #{file}")
      FileUtils.rm(file, force: true)
    end
  end
end
