SELECT id,
       pool_id,
       post_ids,
       added_post_ids,
       removed_post_ids,
       updater_id,
       description,
       description_changed,
       name,
       name_changed,
       created_at,
       updated_at,
       is_active,
       version
FROM public.pool_versions
