SELECT id,
       post_id,
       tags,
       added_tags,
       removed_tags,
       locked_tags,
       added_locked_tags,
       removed_locked_tags,
       updater_id,
       updated_at,
       rating,
       rating_changed,
       parent_id,
       parent_changed,
       source,
       source_changed,
       description,
       description_changed,
       version,
       reason,
       original_tags
FROM public.post_versions
